In [1]:
import pandas as pd 
import numpy as np

In [2]:
index = ['India', 'USA', 'China', 'Japan', 'Germany']
data = [1000, 2000, 3000, 4000, 5000]
ser = pd.Series(index = index, data = data)
ser

India      1000
USA        2000
China      3000
Japan      4000
Germany    5000
dtype: int64

Series form a dictionary

In [3]:
dict = {'India': 1000, 'USA': 2000, 'China': 3000, 'Japan': 4000, 'Germany': 5000}
ser = pd.Series(dict)
ser

India      1000
USA        2000
China      3000
Japan      4000
Germany    5000
dtype: int64

In [5]:
# Imaginary Sales Data for 1st and 2nd Quarters for Global Company
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [6]:
sales_q1 = pd.Series(q1)
sales_q2 = pd.Series(q2)

In [7]:
sales_q1['Japan']

np.int64(80)

In [8]:
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [ ]:
#Broadcasting in Pandas
#Normally [1,2]*2 = [1,2,1,2] but in Pandas it will multiply each element by 2
sales_q1 = sales_q1 * 2
sales_q1

Japan     320
China    1800
India     800
USA      1000
dtype: int64

In [12]:
totalSales= sales_q1 + sales_q2
totalSales

Brazil       NaN
China     2300.0
India     1010.0
Japan        NaN
USA       1260.0
dtype: float64

In [27]:
sales_q1.add(sales_q2, fill_value=0)

Brazil     100.0
China     2300.0
India     1010.0
Japan      320.0
USA       1260.0
dtype: float64

DATAFRAMES

In [15]:
np.random.seed(98)
data = np.random.randint(1, 100, (3,4))
data

array([[91, 43, 53, 64],
       [92, 90, 66, 69],
       [72, 39,  3, 24]])

In [16]:
index = ['MH', 'GJ', 'RJ']
columns = ['Jan', 'Feb', 'Mar', 'Apr']

In [19]:
df = pd.DataFrame(data = data , index = index, columns = columns)
df

    Jan  Feb  Mar  Apr
MH   91   43   53   64
GJ   92   90   66   69
RJ   72   39    3   24

In [20]:
df.info

<bound method DataFrame.info of     Jan  Feb  Mar  Apr
MH   91   43   53   64
GJ   92   90   66   69
RJ   72   39    3   24>

In [ ]:
from pathlib import Path
import pandas as pd

candidate_paths = [
    Path("03-Pandas/tips.csv"),
    Path("/Users/arnavdeshpande/Engineering DB/Python_For_ML/03-Pandas/tips.csv"),
    Path("/content/03-Pandas/tips.csv"),
    Path("/content/tips.csv"),
]

for csv_path in candidate_paths:
    if csv_path.exists():
        df = pd.read_csv(csv_path)
        break
else:
    raise FileNotFoundError("tips.csv was not found in any expected notebook path. If you are running in /content, upload the file there or mount the project folder.")

df

['.config', 'sample_data']